export const ActionTypes = {
    
    CREATE_PRODUCT:"CREATE_PRODUCT",
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    EDIT_PRODUCT : "EDIT_PRODUCT",
    DELETE_PRODUCT : "DELETE_PRODUCT",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT",
    CREATE_CATEGORY : "CREATE_CATEGORY", 
    SET_CATEGORIES : "SET_CATEGORIES",
    SELECTED_CATEGORY : "SELECTED_CATEGORY",
    EDIT_CATEGORY : "EDIT_CATEGORY",
    DELETE_CATEGORY : "DELETE_CATEGORY", 
    CREATE_CART : "CREATE_CART",
    SET_CARTS : "SET_CARTS",
    SELECTED_CART : "SELECTED_CART",
    EDIT_CART : "EDIT_CART",
    DELETE_CART : "DELETE_CART",

    SET_USER : "SET_USER",
    CREATE_USER : "CREATE_USER",
    GET_USER_ID : "GET_USER_ID" 
    
}